### ISSUE TITLE
Error not caught by .catch 

### ISSUE THREAD

**Issue by drgroot** [grantholle/rarbg#3]
I noticed sometimes we get an error that is not catched by the .catch method

rarbg.search(...).then(...).catch(...)

```
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.res.on (path/node_modules/rarbg/index.js:131:42)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by grantholle** [comment]
Thanks for the issue. I believe this is fixed in version 1.1.1

**Comment by drgroot** [comment]
Using version 1.1.1, still not fixed

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.res.on (/home/mrsunnycare/theporndb/node_modules/rarbg/index.js:135:33)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by grantholle** [comment]
Could I have a code sample?

**Comment by drgroot** [comment]
Sure,

```
var search = "Black Mamba 17.08.12";
rarbg.search({
        search_string:search,
        sort:'seeders',
        min_seeders: 10
 }).then( data=> res.send( JSON.stringify(data) ) )
.catch( function(e){
      res.send( JSON.stringify([]) );
});
```

**Comment by florianmski** [comment]
I have observed the same, seems to work via curl though.
Seems we also now obligatory needs an `app_id`

**Comment by grantholle** [comment]
@florianmski Yeah, there's a fix in 1.2, but it's not letting me publish it. I have submitted a ticket to npm to see what the issue is. If you `npm i https://github.com/grantholle/rarbg/`, it will pull the changes with `app_id`

**Comment by drgroot** [comment]
Your right, my package json file was not the right version of the api. Very sorry for inconvience.

**Comment by grantholle** [comment]
@florianmski version 1.2.1 is available from npm now
